# P4

In [3]:
%load_ext autoreload

In [4]:
%autoreload 2
# from src import eliminacion_gaussiana, gauss_jordan
# las funciones se encuentran disponibles como referencia

In [5]:
import logging
from sys import stdout
from datetime import datetime
import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[08-14 08:29:32][INFO] 2024-08-14 08:29:32.539263


In [6]:
# ####################################################################
def gauss_jordan(Ab: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de Gauss-Jordan.

    ## Parameters

    ``Ab``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """
    if not isinstance(Ab, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        Ab = np.array(Ab)
    assert Ab.shape[0] == Ab.shape[1] - 1, "La matriz A debe ser de tamaño n-by-(n+1)."
    n = Ab.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if Ab[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(Ab[pi, i]) < abs(Ab[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = Ab[i, :].copy()
            Ab[i, :] = Ab[p, :].copy()
            Ab[p, :] = _aux

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = Ab[j, i] / Ab[i, i]
            Ab[j, i:] = Ab[j, i:] - m * Ab[i, i:]

        logging.info(f"\n{Ab}")

    if Ab[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    # --- Sustitución hacia atrás
    solucion = np.zeros(n)

    for i in range(n - 1, -1, -1):
        solucion[i] = Ab[i, -1] / Ab[i, i]

    return solucion

In [7]:
%autoreload 2
from src import matriz_aumentada

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b)
gauss_jordan(Ab)

[08-14 08:29:47][INFO] 2024-08-14 08:29:47.342023
[08-14 08:29:47][INFO] 2024-08-14 08:29:47.359169
[08-14 08:29:47][INFO] 2024-08-14 08:29:47.362870
[08-14 08:29:47][INFO] 2024-08-14 08:29:47.366366
[08-14 08:29:47][INFO] 
[[ 1.  2.  3.  4.  1.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0. -1. -3. -6.  0.]]
[08-14 08:29:47][INFO] 
[[ 1.  0.  3.  6.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0. -3. -7. -4.]]
[08-14 08:29:47][INFO] 
[[ 1.  0.  0. -3.  9.]
 [ 0.  1.  0. -1. -4.]
 [ 0.  0. -1. -3.  0.]
 [ 0.  0.  0.  2. -4.]]
[08-14 08:29:47][INFO] 
[[ 1.  0.  0.  0.  3.]
 [ 0.  1.  0.  0. -6.]
 [ 0.  0. -1.  0. -6.]
 [ 0.  0.  0.  2. -4.]]


array([ 3., -6.,  6., -2.])

In [16]:
# ####################################################################
def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante método de Gauss-Jordan.
    ## Parameters
    ``A``: matriz cuadrada de tamaño n x n.

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    A = np.array(A)
    n = A.shape[0]
    I = np.eye(n)
    Ab = matriz_aumentada(A, I)
    
    if not isinstance(Ab, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        Ab = np.array(Ab)
    
    assert Ab.shape[0] == Ab.shape[1] // 2, "La matriz A debe ser de tamaño n-by-n."
    
    for i in range(n):  # loop por columna
        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if Ab[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(Ab[pi, i]) > abs(Ab[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            Ab[[i, p]] = Ab[[p, i]]

        # --- Normalizar fila pivote
        Ab[i] = Ab[i] / Ab[i, i]

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = Ab[j, i]
            Ab[j] = Ab[j] - m * Ab[i]

        logging.info(f"\n{Ab}")

    if Ab[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    # Extraer la parte derecha de la matriz aumentada
    A_inv = Ab[:, n:]

    return A_inv

## Ejemplos 
Compruebe su función con respecto a los siguientes ejemplos:
* Ejemplo 1

In [18]:
# La matriz A =
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]
inv_matrix(A)

[08-14 08:48:08][INFO] 2024-08-14 08:48:08.143431
[08-14 08:48:08][INFO] 
[[ 1.    1.75  2.25  2.5   0.    0.    0.    0.25]
 [ 0.    1.5   1.5   2.    0.    1.    0.   -0.5 ]
 [ 0.    0.75  1.25  1.5   0.    0.    1.   -0.75]
 [ 0.    0.25  0.75  1.5   1.    0.    0.   -0.25]]
[08-14 08:48:08][INFO] 
[[ 1.          0.          0.5         0.16666667  0.         -1.16666667
   0.          0.83333333]
 [ 0.          1.          1.          1.33333333  0.          0.66666667
   0.         -0.33333333]
 [ 0.          0.          0.5         0.5         0.         -0.5
   1.         -0.5       ]
 [ 0.          0.          0.5         1.16666667  1.         -0.16666667
   0.         -0.16666667]]
[08-14 08:48:08][INFO] 
[[ 1.          0.          0.         -0.33333333  0.         -0.66666667
  -1.          1.33333333]
 [ 0.          1.          0.          0.33333333  0.          1.66666667
  -2.          0.66666667]
 [ 0.          0.          1.          1.          0.         -1.
   2.  

array([[ 0.5, -0.5, -1.5,  1.5],
       [-0.5,  1.5, -1.5,  0.5],
       [-1.5, -1.5,  3.5, -1.5],
       [ 1.5,  0.5, -1.5,  0.5]])

* Ejemplo 2

In [19]:
# La matriz A =
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
inv_matrix(A)

[08-14 08:48:18][INFO] 
[[ 1.    1.    1.25  0.25  0.25  0.    0.    0.  ]
 [ 0.    1.   -1.75  1.25 -0.75  1.    0.    0.  ]
 [ 0.   -1.    1.5   0.5  -0.5   0.    1.    0.  ]
 [ 0.   -1.    1.25  3.25 -0.75  0.    0.    1.  ]]
[08-14 08:48:18][INFO] 
[[ 1.    0.    3.   -1.    1.   -1.    0.    0.  ]
 [ 0.    1.   -1.75  1.25 -0.75  1.    0.    0.  ]
 [ 0.    0.   -0.25  1.75 -1.25  1.    1.    0.  ]
 [ 0.    0.   -0.5   4.5  -1.5   1.    0.    1.  ]]
[08-14 08:48:18][INFO] 
[[  1.    0.    0.   26.   -8.    5.    0.    6. ]
 [  0.    1.    0.  -14.5   4.5  -2.5   0.   -3.5]
 [ -0.   -0.    1.   -9.    3.   -2.   -0.   -2. ]
 [  0.    0.    0.   -0.5  -0.5   0.5   1.   -0.5]]
[08-14 08:48:18][INFO] 
[[  1.   0.   0.   0. -34.  31.  52. -20.]
 [  0.   1.   0.   0.  19. -17. -29.  11.]
 [ -0.  -0.   1.   0.  12. -11. -18.   7.]
 [ -0.  -0.  -0.   1.   1.  -1.  -2.   1.]]


array([[-34.,  31.,  52., -20.],
       [ 19., -17., -29.,  11.],
       [ 12., -11., -18.,   7.],
       [  1.,  -1.,  -2.,   1.]])

# Ejercicios
* Ejercicio 1

In [24]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
inv_matrix(A)

[08-14 08:50:29][INFO] 
[[ 1.    0.    0.    1.25  0.25  0.    0.    0.  ]
 [ 0.    0.    4.   -1.25 -0.25  1.    0.    0.  ]
 [ 0.    4.    1.   -0.75 -0.75  0.    1.    0.  ]
 [ 0.    3.    3.   -1.25 -0.25  0.    0.    1.  ]]
[08-14 08:50:29][INFO] 
[[ 1.      0.      0.      1.25    0.25    0.      0.      0.    ]
 [ 0.      1.      0.25   -0.1875 -0.1875  0.      0.25    0.    ]
 [ 0.      0.      4.     -1.25   -0.25    1.      0.      0.    ]
 [ 0.      0.      2.25   -0.6875  0.3125  0.     -0.75    1.    ]]
[08-14 08:50:29][INFO] 
[[ 1.        0.        0.        1.25      0.25      0.        0.
   0.      ]
 [ 0.        1.        0.       -0.109375 -0.171875 -0.0625    0.25
   0.      ]
 [ 0.        0.        1.       -0.3125   -0.0625    0.25      0.
   0.      ]
 [ 0.        0.        0.        0.015625  0.453125 -0.5625   -0.75
   1.      ]]
[08-14 08:50:29][INFO] 
[[  1.   0.   0.   0. -36.  45.  60. -80.]
 [  0.   1.   0.   0.   3.  -4.  -5.   7.]
 [  0.   0.   1.   0.  

array([[-36.,  45.,  60., -80.],
       [  3.,  -4.,  -5.,   7.],
       [  9., -11., -15.,  20.],
       [ 29., -36., -48.,  64.]])

* Ejercicio 2

In [23]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0]
]
inv_matrix(A)

[08-14 08:50:02][INFO] 
[[ 1.   0.   0.   0.   0.   0.5  1.   0.   0.   0.   0.   0.   0.   0.
   0.   0.5]
 [ 0.   1.  -1.   1.   0.  -1.   0.   1.   0.   1.   0.   0.   0.   0.
   0.   0. ]
 [ 0.  -1.   0.   0.   2.   1.5  1.   0.   0.   0.   1.   0.   0.   0.
   0.   0.5]
 [ 0.  -1.  -1.   1.   2.   0.5  1.   1.   0.   0.   0.   1.   0.   0.
   0.   0.5]
 [ 0.   1.   1.   0.  -1.  -0.5  1.   2.   0.   0.   0.   0.   1.   0.
   0.   0.5]
 [ 0.   1.   0.   0.  -1.  -1.   0.   0.   0.   0.   0.   0.   0.   1.
   0.   0. ]
 [ 0.  -1.  -1.   1.   2.   0.5 -1.   2.   0.   0.   0.   0.   0.   0.
   1.  -0.5]
 [ 0.   0.   0.   0.   0.   0.   1.  -1.   1.   0.   0.   0.   0.   0.
   0.   0. ]]
[08-14 08:50:02][INFO] 
[[ 1.   0.   0.   0.   0.   0.5  1.   0.   0.   0.   0.   0.   0.   0.
   0.   0.5]
 [ 0.   1.  -1.   1.   0.  -1.   0.   1.   0.   1.   0.   0.   0.   0.
   0.   0. ]
 [ 0.   0.  -1.   1.   2.   0.5  1.   1.   0.   1.   1.   0.   0.   0.
   0.   0.5]
 [ 0.   0.  -2.   2.   2.  

array([[ 2., -1.,  0., -1.,  0.,  2.,  2., -1.],
       [ 0.,  1.,  1., -1.,  0.,  0.,  0.,  0.],
       [ 6., -1.,  0., -3.,  1.,  1.,  4., -3.],
       [ 6.,  1., -1., -3.,  1., -3.,  3., -3.],
       [ 2., -1.,  1., -1.,  0.,  3.,  2., -1.],
       [-2.,  2., -0.,  0., -0., -4., -2.,  1.],
       [-1., -0., -0.,  1., -0., -0., -1.,  1.],
       [-2., -0., -0.,  1., -0., -0., -1.,  1.]])

* Ejercicio 3

In [22]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
inv_matrix(A)

[08-14 08:48:54][INFO] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.  1.  0.  1.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.  1.  0.  0.  0.  1.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1. -1.  0.  0.  0.  0.  1.  0.  0.
   0.  0.]
 [ 0.  1.  1.  0.  2.  0. -1.  0. -2.  2. -1.  0.  0.  0.  0.  0.  1.  0.
   0.  0.]
 [ 0.  1.  1.  1.  1.  0.  1.  2. -1.  1. -1.  0.  0.  0.  0.  0.  0.  1.
   0.  0.]
 [ 0.  1.  1.  1.  2.  0. -1.  0. -1.  1. -1.  0.  0.  0.  0.  0.  0.  0.
   1.  0.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.]]
[08-14 08:48:54][INFO] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0. -1

array([[ 14.,  -8.,   9.,  -4.,   0.,  -4.,   9.,   7.,  -8.,   3.],
       [ -2.,   2.,  -1.,   2.,   1.,   1.,  -1.,  -1.,   1.,  -2.],
       [-27.,  14., -18.,   5.,  -2.,   7., -17., -13.,  16.,  -2.],
       [ 12.,  -6.,   8.,  -2.,   1.,  -3.,   7.,   6.,  -7.,   0.],
       [  6.,  -4.,   4.,  -2.,   0.,  -2.,   4.,   3.,  -3.,   2.],
       [ 18.,  -9.,  12.,  -4.,   1.,  -5.,  11.,   9., -11.,   1.],
       [  8.,  -4.,   5.,  -1.,   1.,  -2.,   5.,   4.,  -5.,   0.],
       [ -5.,   2.,  -3.,   0.,  -1.,   1.,  -3.,  -2.,   3.,   1.],
       [-11.,   5.,  -7.,   1.,  -2.,   2.,  -7.,  -5.,   7.,   1.],
       [  1.,  -1.,   1.,  -1.,  -1.,  -1.,   1.,   1.,  -1.,   1.]])